# Generated by Django 3.1.6 on 2021-02-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
